version: '3.4'
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - /Users/daddy/WebstormProjects/elk-docker/elk/logstash/12-performance-data.conf:/etc/logstash/conf.d/12-performance-data.conf

